global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Placeholder jobs for application services. Replace with real metrics endpoints when available.
  - job_name: "api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api:8080"]

  - job_name: "ml-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["ml-service:8082"]

